### ISSUE TITLE
Remove LICENSE ?

### ISSUE THREAD

**Issue by eddelbuettel** [ess-intro/ess-intro.github.io#1]
I have a semi-strong preference for GPL over MIT, but don't want to make it a fight.  I think we simply do not need one here at this website repo.

Individual work is and should be copyright by their individual creators. I do not think we have a group policy.  So I suggest to remove the file.

**Comment by aezarebski** [comment]
Easy, it's been removed along with the old HTML, I hadn't realised Rmarkdown was that easy to use.

**Comment by eddelbuettel** [comment]
`pandoc` _rocks_.  I really quite like using (essentially just) it for conversion.  The stanza by the `rmarkdown` package also added a `knitr` block but we really don't use or need it.
